from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, IncludeLaunchDescription, SetEnvironmentVariable, TimerAction, LogInfo
from launch.substitutions import Command, LaunchConfiguration, PathJoinSubstitution, PythonExpression
from launch_ros.actions import Node
from launch_ros.substitutions import FindPackageShare
from launch.launch_description_sources import PythonLaunchDescriptionSource
from ament_index_python.packages import get_package_share_directory, get_package_prefix
import os
from launch_ros.parameter_descriptions import ParameterValue
from launch.actions import RegisterEventHandler
from launch.event_handlers import OnProcessExit

def generate_launch_description():
    
    #ARGUMENTS ===========================================================================

    description_dir = get_package_share_directory("deliverybot_description")
    controllers_dir = get_package_share_directory("deliverybot_controllers")
    teleop_dir = get_package_share_directory("deliverybot_teleop")
    localization_dir = get_package_share_directory("deliverybot_localization")
    sensors_dir = get_package_share_directory("deliverybot_sensors")
    mapping_dir = get_package_share_directory("deliverybot_mapping")
    bringup_dir = get_package_share_directory("deliverybot_bringup")

    gazebo_ros_dir = get_package_share_directory("gazebo_ros")
    gazebo_config = os.path.join(bringup_dir, 'config', 'gazebo_config.yaml')

    #GAZEBO VERSION ******************************************

    gazebo_version_arg = DeclareLaunchArgument(
        name='gazebo_version',
        default_value='classic',
        description='Gazebo flavor to use: [classic|ignition|gz]'
    )   
    #*********************************************************

    use_sim_time_arg = DeclareLaunchArgument(
        name="use_sim_time",
        default_value="true",
        description="simulation time. true if inputs are generated by gazebo"
    )

    urdf_path_arg = DeclareLaunchArgument(
        name="model",
        default_value=os.path.join(description_dir, "urdf", "deliverybot.urdf.xacro"),
        description="Absolute path to robot urdf file"
    )
    
    world_name_arg = DeclareLaunchArgument(
        name="world_name",
        default_value="empty",
        description="World file name"
    )

    rviz_config_arg = DeclareLaunchArgument(
        name="rviz_config",
        default_value=os.path.join(
            bringup_dir,
            "rviz",
            "display_bringup.rviz"
        ),
        description="Absolute path to rviz config"
    )

    world_path = PathJoinSubstitution([
        bringup_dir,
        "worlds",
        PythonExpression(["'", LaunchConfiguration("world_name"), "'", " + '.world'"])
    ])

    urdf_path = os.path.join(description_dir, "models")
    urdf_path += os.pathsep + os.path.join(get_package_prefix("deliverybot_description"), "share")
    env_var = SetEnvironmentVariable("GAZEBO_MODEL_PATH", urdf_path)
    gazebo_version = LaunchConfiguration("gazebo_version")
    rviz_config = LaunchConfiguration("rviz_config")
    use_sim_time = LaunchConfiguration("use_sim_time")

    robot_description = Command([
        'xacro ', LaunchConfiguration('model'),
        ' gazebo_version:=', LaunchConfiguration('gazebo_version')
    ])


    #LAUNCH =================================================================================================

    # Robot state publisher
    robot_state_publisher = Node(
        package="robot_state_publisher",
        executable="robot_state_publisher",
        parameters=[
            {"robot_description": robot_description},
            {"use_sim_time": use_sim_time}
        ]   
    )

    # Gazebo
    gazebo_launch = IncludeLaunchDescription(
        PythonLaunchDescriptionSource(
            os.path.join(bringup_dir, "launch", "gazebo.launch.py")
        ),
        launch_arguments={
            "gazebo_version": gazebo_version,
            "world_path" : world_path,
            "use_sim_time" : use_sim_time
        }.items()
    )

    # Rviz2
    rviz2 = Node(
        package="rviz2",
        executable="rviz2",
        name="rviz2",
        output="screen",
        parameters=[{'use_sim_time': True}],
        arguments=[
            "-d", rviz_config
        ]
    )

    # Lidar fusion 
    lidar_fusion = IncludeLaunchDescription(
        PythonLaunchDescriptionSource(
            os.path.join(sensors_dir, "launch", "sensors.launch.py")
        )
    )


    # Teleop and twistmux
    teleoperation = IncludeLaunchDescription(
        PythonLaunchDescriptionSource(
            os.path.join(teleop_dir, "launch", "teleop.launch.py")
        ),
        launch_arguments={
            "use_sim_time": 'true'
        }.items()
    )
    
    # Twistmux speed monitoring
    twistmux_speed_monitoring = IncludeLaunchDescription(
            PythonLaunchDescriptionSource(
                os.path.join(teleop_dir, "launch", "twistmux_speed_monitoring.launch.py")
            )
        )

    # Convert twistmux output to TwistStamped
    twist_to_twist_stamped_and_safety_node = Node(
            package='deliverybot_teleop',
            executable='twist_to_twist_stamped_and_safety.py',
            name='twist_controller_stamped',
            parameters=[
                {'input_unstamped_topic' : 'cmd_vel_ack'},
                {'output_stamped_topic': 'cmd_vel_ack_stamped'},
                {'frame_id':'base_link'},
                {'safety_stop_topic': 'safety_stop'},
                {'safety_warning_topic': 'safety_warning'},
            ]
        )

    # Controllers
    controllers = IncludeLaunchDescription(
        PythonLaunchDescriptionSource(
            os.path.join(controllers_dir, "launch", "controllers.launch.py")
        ),
        launch_arguments={
            "use_sim_time" : use_sim_time
        }.items(),
    )

    # EKF Local Localization - Odom from Ackermann + sensor fusion IMU
    local_localization = IncludeLaunchDescription(
        PythonLaunchDescriptionSource(
            os.path.join(localization_dir, "launch", "local_localization.launch.py")
        )
    )

    # Graph SLAM 
    graph_slam = IncludeLaunchDescription(
        PythonLaunchDescriptionSource(
            os.path.join(mapping_dir, "launch", "graph_slam.launch.py")
        )
    )
   
    
    return LaunchDescription([
        use_sim_time_arg,
        env_var,
        urdf_path_arg,
        world_name_arg,
        rviz_config_arg,
        gazebo_version_arg,

        gazebo_launch,

        TimerAction(
            actions=[

                controllers,
                robot_state_publisher,
                rviz2,
                #lidar_fusion,
                teleoperation,
                twistmux_speed_monitoring,
                #twist_to_twist_stamped_and_safety_node,
                #local_localization
                #graph_slam
                
                
            ],
            period=3.0  
        )
    ])


