controller_manager:
  ros__parameters:
    update_rate: 1000 # Hz
    use_sim_time: true # For simulated robots

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    ackermann_steering_controller:
      type: ackermann_steering_controller/AckermannSteeringController


ackermann_steering_controller:
  ros__parameters:
    reference_timeout: 2.0
    front_steering: true
    open_loop: false
    velocity_rolling_window_size: 10
    position_feedback: true

    use_stamped_vel: true

    rear_wheels_names: ["wheel_rear_right_joint", "wheel_rear_left_joint"]
    front_wheels_names: ["steering_right_joint", "steering_left_joint"]
    wheel_params_from_collision_mesh: true

    wheelbase: 0.663378 # Distance between the front and rear axles of the robot
    front_wheel_track: 1.413834 #1.353834 # Distance between the left and right front wheels
    rear_wheel_track: 1.413834 #  Distance between the left and right rear wheels
    front_wheels_radius: 0.226428 # Radius of the wheels
    rear_wheels_radius: 0.226428 # Radius of the wheels

    wheel_separation: 1.413834
    max_steering_angle: 0.785  # 45 degrees in radians
    min_steering_angle: -0.785

    steering_slow_down_factor: 1.5 #1.0 no slowdown
    angular_velocity_filter: 0.3

    enable_odom_tf: true
    odom_frame_id: odom
    base_frame_id: base_link
    cmd_topic: "cmd_vel_stamped"
    cmd_type: "geometry_msgs/msg/TwistStamped"

    publish_rate: 50

  