joy_node:
  ros__parameters:
    deadzone: 0.05
    autorepeat_rate: 20.0
    dev: '/dev/input/js1' #from jstest-gtk


teleop_node:
  ros__parameters:

    axis_linear:
      x: 1
    scale_linear:
      x: 0.5
    scale_linear_turbo:
      x: 1.0
    
    axis_angular:
      yaw: 0
    scale_angular:
      yaw: 0.5
    scale_angular_turbo:
      yaw: 1.0
    
    enable_button: 2
    enable_turbo_button: 5
    require_enable_button: true

    
