joystick:
  ros__parameters:
    priority: True
    turbo:
      linear_forward_min: 0.2
      linear_forward_max: 1.0
      linear_backward_min: 0.2
      linear_backward_max: 1.0
      angular_min: 0.7
      angular_max: 5.0
      steps: 3 #higher step values for smoother speed changes
      