<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <!-- Links -->
 <!-- Macro for LiDAR links and joints -->
 <xacro:macro name="lidar_sensor" params="name prefix_x prefix_y yaw_multiplier">

    <link name="${name}_base_link">
        <xacro:lidar_inertial/>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 ${yaw_multiplier * lidar_offset_yaw}" />
            <geometry>
                <mesh filename="package://deliverybot_description/meshes/lidar.obj" />
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 ${yaw_multiplier * lidar_offset_yaw}" />
            <geometry>
                <mesh filename="package://deliverybot_description/meshes/lidar.stl" />
            </geometry>
        </collision>
    </link>

    <link name="${name}_link"/>

    <joint name="${name}_base_joint" type="fixed">
        <origin xyz="${prefix_x * lidar_offset_x} ${prefix_y * lidar_offset_y} ${body_lidar_offset_z}" rpy="0 0 0" />
        <parent link="body_link" />
        <child link="${name}_base_link" />
    </joint>

    <joint name="${name}_joint" type="fixed">
        <origin xyz="0 0 ${lidar_sensor_offset_z}" rpy="0 0 ${yaw_multiplier * lidar_offset_yaw}" />
        <parent link="${name}_base_link" />
        <child link="${name}_link" />
    </joint>
</xacro:macro>

<!-- Use the macro for each LiDAR -->
<xacro:lidar_sensor name="lidar_front_left"  prefix_x="1"  prefix_y="1"  yaw_multiplier="1"/>
<xacro:lidar_sensor name="lidar_front_right" prefix_x="1"  prefix_y="-1" yaw_multiplier="-1"/>
<xacro:lidar_sensor name="lidar_rear_left"   prefix_x="-1" prefix_y="1"  yaw_multiplier="3"/>
<xacro:lidar_sensor name="lidar_rear_right"  prefix_x="-1" prefix_y="-1" yaw_multiplier="-3"/>

    
    <!-- Plugins-->
    <xacro:macro name="lidar_sensor" params="name">
        <gazebo reference="${name}_link">
            <sensor type="gpu_ray" name="${name}">
                <pose>0 0 0 0 0 0</pose>
                <visualize>false</visualize>
                <update_rate>5</update_rate>
                <ray>
                    <scan>
                        <horizontal>
                            <samples>100</samples>
                            <resolution>1</resolution>
                            <min_angle>-1.57</min_angle> <!-- -90 degrees -->
                            <max_angle>1.57</max_angle>  <!-- 90 degrees -->
                        </horizontal>
                        <vertical>
                            <samples>16</samples>
                            <resolution>1</resolution>
                            <min_angle>-0.1308996939</min_angle> <!-- -7.5 degrees -->
                            <max_angle>0.1308996939</max_angle>  <!-- 7.5 degrees -->
                        </vertical>
                    </scan>
                    <range>
                        <min>0.10</min>
                        <max>20.0</max>
                        <resolution>0.05</resolution>
                    </range>
                    <noise>
                        <type>gaussian</type>
                        <mean>0.0</mean>
                        <stddev>0.01</stddev>
                    </noise>
                </ray>
                <plugin name="gazebo_ros_${name}_controller" filename="libgazebo_ros_ray_sensor.so">
                    <ros>
                        <namespace>/</namespace>
                        <remapping>~/out:=${name}/points</remapping>
                    </ros>
                    <output_type>sensor_msgs/PointCloud2</output_type>
                    <frame_name>${name}_link</frame_name>
                </plugin>
            </sensor>
        </gazebo>
    </xacro:macro>

    <!-- Use the macro for each LiDAR -->
    <xacro:lidar_sensor name="lidar_front_left"/>
    <xacro:lidar_sensor name="lidar_front_right"/>
    <xacro:lidar_sensor name="lidar_rear_left"/>
    <xacro:lidar_sensor name="lidar_rear_right"/>

</robot>
