<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <!-- Links -->

 <!-- Reference link for the fused pointcloud-->
  <link name="central_lidar_link">
    <xacro:scan_inertial/>
    <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
            <mesh filename="package://deliverybot_description/meshes/scan.obj" />
        </geometry>
    </visual>
    <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
            <mesh filename="package://deliverybot_description/meshes/scan.stl" />
        </geometry>
    </collision>
  </link> 
  
  <joint name="body_central_lidar_joint" type="fixed">
    <origin xyz="0 0 ${central_lidar_offset_z}" rpy="0 0 0" />
        <parent link="body_link" />
        <child link="central_lidar_link" />
  </joint>
  
 <!-- Macro for LiDAR links and joints -->
 <xacro:macro name="lidar_sensor" params="name prefix_x prefix_y yaw_multiplier">

    <link name="${name}_support_link">
        <xacro:lidar_inertial/>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 ${yaw_multiplier * lidar_offset_yaw}" />
            <geometry>
                <mesh filename="package://deliverybot_description/meshes/lidar.obj" />
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 ${yaw_multiplier * lidar_offset_yaw}" />
            <geometry>
                <mesh filename="package://deliverybot_description/meshes/lidar.stl" />
            </geometry>
        </collision>
    </link>

    <link name="${name}_link"/>

    <joint name="${name}_support_joint" type="fixed">
        <origin xyz="${prefix_x * lidar_offset_x} ${prefix_y * lidar_offset_y} ${body_lidar_offset_z}" rpy="0 0 0" />
        <parent link="body_link" />
        <child link="${name}_support_link" />
    </joint>

    <joint name="${name}_joint" type="fixed">
        <origin xyz="${prefix_x * lidar_offset_x} ${prefix_y * lidar_offset_y} ${lidar_sensor_offset_z}" rpy="0 0 ${yaw_multiplier * lidar_offset_yaw}" />
        <parent link="body_link" />
        <child link="${name}_link" />
    </joint>
</xacro:macro>

<!-- Use the macro for each LiDAR -->
<xacro:lidar_sensor name="lidar_front_left"  prefix_x="1"  prefix_y="1"  yaw_multiplier="1"/>
<xacro:lidar_sensor name="lidar_front_right" prefix_x="1"  prefix_y="-1" yaw_multiplier="-1"/>
<xacro:lidar_sensor name="lidar_rear_left"   prefix_x="-1" prefix_y="1"  yaw_multiplier="3"/>
<xacro:lidar_sensor name="lidar_rear_right"  prefix_x="-1" prefix_y="-1" yaw_multiplier="-3"/>

    
<!-- Plugins-->
<xacro:if value="${gazebo_version == 'classic'}">
    <xacro:macro name="lidar_sensor" params="name">
        <gazebo reference="${name}_link">
            <sensor type="gpu_ray" name="${name}">
                <pose>0 0 0 0 0 0</pose>
                <visualize>false</visualize>
                <always_on>true</always_on>
                <update_rate>5</update_rate>
                <ray>
                    <scan>
                        <horizontal>
                            <samples>100</samples>
                            <resolution>1</resolution>
                            <min_angle>-1.04</min_angle> <!-- -60 degrees -->
                            <max_angle>1.04</max_angle>  <!-- 60 degrees -->
                        </horizontal>
                        <vertical> 
                            <samples>32</samples>
                            <resolution>1</resolution>
                            <min_angle>-0.436</min_angle> <!-- -25 degrees -->
                            <max_angle>0.1308</max_angle>  <!-- 7.5 degrees -->
                        </vertical>
                    </scan>
                    <range>
                        <min>0.10</min>
                        <max>20.0</max>
                        <resolution>0.02</resolution>
                    </range>
                    <!-- <noise>
                        <type>gaussian</type>
                        <mean>0.0</mean>
                        <stddev>0.01</stddev>
                    </noise> -->
                </ray>

                <!-- GAZEBO CLASSIC PLUGIN-->
                <plugin name="gazebo_ros_${name}_controller" filename="libgazebo_ros_ray_sensor.so">
                    <ros>
                        <namespace>/</namespace>
                        <remapping>~/out:=${name}/points</remapping>
                    </ros>
                    <output_type>sensor_msgs/PointCloud2</output_type>
                    <frame_name>${name}_link</frame_name>
                </plugin>
            </sensor>
        </gazebo>
    </xacro:macro>
    </xacro:if>

<xacro:if value="${gazebo_version == 'ignition'}">
    <xacro:macro name="lidar_sensor" params="name">
       <gazebo reference="${name}_link">
        <sensor name="${name}" type="gpu_lidar">
            <ignition_frame_id>${name}_link</ignition_frame_id>
            <pose relative_to="${name}_link">0 0 0 0 0 0</pose>
            <topic>${name}/scan</topic>
            <update_rate>10</update_rate>
            <ray>
                <scan>
                    <horizontal>
                        <samples>100</samples>
                        <resolution>1</resolution>
                        <min_angle>-1.04</min_angle> <!-- -60 degrees -->
                        <max_angle>1.04</max_angle>  <!-- 60 degrees -->
                    </horizontal>
                    <vertical>
                        <samples>32</samples>
                        <resolution>1</resolution>
                        <min_angle>-0.436</min_angle> <!-- -25 degrees -->
                        <max_angle>0.1308</max_angle>  <!-- 7.5 degrees -->
                    </vertical>
                </scan>
                <range>
                    <min>0.10</min>
                    <max>20.0</max>
                    <resolution>0.02</resolution>
                </range>
            </ray>
            <always_on>1</always_on>
            <visualize>true</visualize>
        </sensor>
    </gazebo>
    </xacro:macro>
    </xacro:if>

<xacro:if value="${gazebo_version == 'gz'}">
    <xacro:macro name="lidar_sensor" params="name">
       <gazebo reference="${name}_link">
        <sensor name="${name}" type="gpu_lidar">"
            <ignition_frame_id>"${name}_link</ignition_frame_id>
            <pose relative_to="${name}_link">0 0 0 0 0 0</pose>
            <topic>${name}/scan</topic>
            <update_rate>10</update_rate>
            <ray>
                <scan>
                    <horizontal>
                        <samples>100</samples>
                        <resolution>1</resolution>
                        <min_angle>-1.04</min_angle> <!-- -60 degrees -->
                        <max_angle>1.04</max_angle>  <!-- 60 degrees -->
                    </horizontal>
                    <vertical>
                        <samples>32</samples>
                        <resolution>1</resolution>
                        <min_angle>-0.436</min_angle> <!-- -25 degrees -->
                        <max_angle>0.1308</max_angle>  <!-- 7.5 degrees -->
                    </vertical>
                </scan>
                <range>
                    <min>0.10</min>
                    <max>20.0</max>
                    <resolution>0.02</resolution>
                </range>
            </ray>
            <always_on>1</always_on>
            <visualize>true</visualize>
        </sensor>
    </gazebo>
    </xacro:macro>
    </xacro:if>


<!-- Use the macro for each LiDAR -->
<xacro:lidar_sensor name="lidar_front_left"/>
<xacro:lidar_sensor name="lidar_front_right"/>
<xacro:lidar_sensor name="lidar_rear_left"/>
<xacro:lidar_sensor name="lidar_rear_right"/>

</robot>