<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <!-- Links -->

 <!-- Reference link for the fused pointcloud-->
  <link name="central_lidar_link"/> 
  
  <joint name="body_central_lidar_joint" type="fixed">
    <origin xyz="0 0 ${body_lidar_offset_z + lidar_sensor_offset_z + central_lidar_offset_z}" rpy="0 0 0" />
        <parent link="body_link" />
        <child link="central_lidar_link" />
  </joint>
  
 <!-- Macro for LiDAR links and joints -->
 <xacro:macro name="lidar_sensor" params="name prefix_x prefix_y yaw_multiplier">

    <link name="${name}_support_link">
        <xacro:lidar_inertial/>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 ${yaw_multiplier * lidar_offset_yaw}" />
            <geometry>
                <mesh filename="package://deliverybot_description/meshes/lidar.obj" />
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 ${yaw_multiplier * lidar_offset_yaw}" />
            <geometry>
                <mesh filename="package://deliverybot_description/meshes/lidar.stl" />
            </geometry>
        </collision>
    </link>

    <link name="${name}_link"/>

    <joint name="${name}_support_joint" type="fixed">
        <origin xyz="${prefix_x * lidar_offset_x} ${prefix_y * lidar_offset_y} ${-lidar_sensor_offset_z - central_lidar_offset_z}" rpy="0 0 0" />
        <parent link="central_lidar_link" />
        <child link="${name}_support_link" />
    </joint>

    <joint name="${name}_joint" type="fixed">
        <origin xyz="${prefix_x * lidar_offset_x} ${prefix_y * lidar_offset_y} ${-central_lidar_offset_z}" rpy="0 0 ${yaw_multiplier * lidar_offset_yaw}" />
        <parent link="central_lidar_link" />
        <child link="${name}_link" />
    </joint>
</xacro:macro>

<!-- Use the macro for each LiDAR -->
<xacro:lidar_sensor name="lidar_front_left"  prefix_x="1"  prefix_y="1"  yaw_multiplier="1"/>
<xacro:lidar_sensor name="lidar_front_right" prefix_x="1"  prefix_y="-1" yaw_multiplier="-1"/>
<xacro:lidar_sensor name="lidar_rear_left"   prefix_x="-1" prefix_y="1"  yaw_multiplier="3"/>
<xacro:lidar_sensor name="lidar_rear_right"  prefix_x="-1" prefix_y="-1" yaw_multiplier="-3"/>

    
<!-- Plugins-->
<xacro:macro name="lidar_sensor" params="name">
    <gazebo reference="${name}_link">
        <sensor name="${name}" type="ray">
            <always_on>true</always_on>
            <update_rate>10</update_rate>
            <visualize>false</visualize>
            <pose>0 0 0 0 0 0</pose>
            <ray>
                <scan>
                <horizontal>
                    <samples>100</samples>       <!-- The velodyne has 32 beams(samples) -->
                    <resolution>1</resolution>
                    <min_angle>-1.5707963</min_angle>
                    <max_angle>1.5707963</max_angle>
                </horizontal>
                <vertical>
                    <samples>16</samples>       <!-- The velodyne has 32 beams(samples) -->
                    <resolution>1</resolution>
                    <min_angle>-0.20</min_angle>
                    <max_angle>0.06</max_angle>
                </vertical>
                </scan>
                <range>
                    <min>0.1</min> <!-- Minimum distance of the beam -->
                    <max>30.0</max>
                <resolution>0.01</resolution>
                </range>
            </ray>
            <plugin name="gazebo_ros_${name}_velodyne_controller" filename="libgazebo_ros_velodyne_laser.so">
                <ros>
                    <namespace>/</namespace>
                    <remapping>~/out:=${name}/points</remapping>
                </ros>
                <frameName>${name}_link</frameName>
                <output_type>sensor_msgs/PointCloud2</output_type>
                <min_range>0.1</min_range>
                <max_range>30</max_range>
                <min_intensity>0.0</min_intensity>
                <gaussianNoise>0.0</gaussianNoise>
            </plugin>
        </sensor>
    </gazebo>
</xacro:macro>

<!-- Use the macro for each LiDAR -->
<xacro:lidar_sensor name="lidar_front_left"/>
<xacro:lidar_sensor name="lidar_front_right"/>
<xacro:lidar_sensor name="lidar_rear_left"/>
<xacro:lidar_sensor name="lidar_rear_right"/>

</robot>
